---
  - hosts: all
    user: root
    tasks:

      - name: Install MySQL server
        apt: name=mysql-server state=latest

      - name: Mysql | Set root password
        shell: debconf-set-selections <<< 'mysql-server mysql-server/root_password password put_your_root_password'

    
